import { Organization } from '../../types';

export const organizationData: Organization[] = [
  {
    id: 'org-1',
    name: 'Infosys | Juniper Networks | GE Healthcare',
    role: 'Software Engineer / Lead',
    startDate: '2006-10',
    endDate: '2014-06',
    colorClass: 'infosys-bar',
    width: '30%',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg',
  },
  {
    id: 'org-2',
    name: 'Amadeus Labs',
    role: 'Development Manager',
    startDate: '2014-07',
    endDate: '2018-07',
    colorClass: 'amadeus-bar',
    width: '18%',
    logoUrl: 'https://1000logos.net/wp-content/uploads/2022/05/Amadeus-Logo.png',
  },
  {
    id: 'org-3',
    name: 'Walmart Labs',
    role: 'Senior Engineering Manager',
    startDate: '2018-08',
    endDate: '2020-10',
    colorClass: 'walmart-bar',
    width: '18%',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Walmart_logo.svg',
  },
  {
    id: 'org-4',
    name: 'PayPal India',
    role: 'Senior Software Development Manager',
    startDate: '2020-11',
    endDate: '2022-02',
    colorClass: 'paypal-bar',
    width: '15%',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/PayPal.svg',
  },
  {
    id: 'org-5',
    name: 'Microsoft India',
    role: 'Group Engineering Manager',
    startDate: '2022-03',
    endDate: null,
    colorClass: 'microsoft-bar',
    width: '22%',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg',
  },
];
